GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "test blog the sequel",
  "author": "tester 2",
  "url": "foo"
}
###
DELETE http://localhost:3003/api/blogs/607dd0c7108b8449a3cc8fe6
###
PUT http://localhost:3003/api/blogs/607ef0d41689bb75ad92e4c4
Content-Type: application/json

{
  "likes": 3.4,
  "url": 1 
}
###
POST http://localhost:3003/api/users 
Content-Type: application/json

{
  "username": "test blog the sequel",
  "name": "tester 2",
  "password": "foo"
}